name: CI

on: [push]

jobs:
  macos:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode:
          - "12.4" # Swift 5.3

    name: "macOS (Xcode ${{ matrix.xcode }})"

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        swift:
          - "5.3"

    name: "Linux (Swift ${{ matrix.swift }})"

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery
